/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  GetHallOfFameAchievements200Response,
  GetHallOfFameTankAchievements200Response,
  GetPlayerAchievements200Response,
  GetPlayerTankAchievements200Response,
  GetVehicles200Response,
  SearchPlayersAndClans200Response,
} from '../models/index.js';
import {
    GetHallOfFameAchievements200ResponseFromJSON,
    GetHallOfFameAchievements200ResponseToJSON,
    GetHallOfFameTankAchievements200ResponseFromJSON,
    GetHallOfFameTankAchievements200ResponseToJSON,
    GetPlayerAchievements200ResponseFromJSON,
    GetPlayerAchievements200ResponseToJSON,
    GetPlayerTankAchievements200ResponseFromJSON,
    GetPlayerTankAchievements200ResponseToJSON,
    GetVehicles200ResponseFromJSON,
    GetVehicles200ResponseToJSON,
    SearchPlayersAndClans200ResponseFromJSON,
    SearchPlayersAndClans200ResponseToJSON,
} from '../models/index.js';

export interface GetHallOfFameAchievementsRequest {
    battles_count: number;
    tier_group: number;
    time_slice: string;
    stat_type: string;
    lang?: string;
    page?: number;
    page_size?: number;
    social_slice?: string;
}

export interface GetHallOfFameTankAchievementsRequest {
    vehicle_cd: number;
    battles_count: number;
    time_slice: string;
    stat_type: string;
    lang?: string;
    page?: number;
    page_size?: number;
    social_slice?: string;
}

export interface GetPlayerAchievementsRequest {
    battles_count: number;
    tier_group: number;
    time_slice: string;
    stat_type: string;
    spa_id: number;
    lang?: string;
    page?: number;
    page_size?: number;
}

export interface GetPlayerTankAchievementsRequest {
    vehicle_cd: number;
    battles_count: number;
    time_slice: string;
    stat_type: string;
    spa_id: number;
    lang?: string;
    page?: number;
    page_size?: number;
    social_slice?: string;
}

export interface GetVehiclesRequest {
    filter_language: string;
}

export interface SearchPlayersAndClansRequest {
    search_str: string;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Returns full player statistics for the Hall of Fame.
     * @summary Get Hall of Fame achievements
     * @param {number} battles_count Minimum number of battles
     * @param {number} tier_group Tier group
     * @param {string} time_slice Period (YYYY-MM)
     * @param {string} stat_type Statistic type
     * @param {string} [lang] Response language
     * @param {number} [page] Page number
     * @param {number} [page_size] Number of items per page
     * @param {string} [social_slice] Social filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getHallOfFameAchievementsRaw(requestParameters: GetHallOfFameAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHallOfFameAchievements200Response>>;

    /**
     * Returns full player statistics for the Hall of Fame.
     * Get Hall of Fame achievements
     */
    getHallOfFameAchievements(requestParameters: GetHallOfFameAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHallOfFameAchievements200Response>;

    /**
     * Returns full player tank statistics for the Hall of Fame.
     * @summary Get Hall of Fame Tank achievements
     * @param {number} vehicle_cd Vehicle ID
     * @param {number} battles_count Minimum number of battles
     * @param {string} time_slice Period (YYYY-MM)
     * @param {string} stat_type Statistic type
     * @param {string} [lang] Response language
     * @param {number} [page] Page number
     * @param {number} [page_size] Number of items per page
     * @param {string} [social_slice] Social filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getHallOfFameTankAchievementsRaw(requestParameters: GetHallOfFameTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHallOfFameTankAchievements200Response>>;

    /**
     * Returns full player tank statistics for the Hall of Fame.
     * Get Hall of Fame Tank achievements
     */
    getHallOfFameTankAchievements(requestParameters: GetHallOfFameTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHallOfFameTankAchievements200Response>;

    /**
     * Returns personal and common achievement statistics for a user.
     * @summary Search achievements by user
     * @param {number} battles_count Minimum number of battles
     * @param {number} tier_group Tier group
     * @param {string} time_slice Period (YYYY-MM)
     * @param {string} stat_type Statistic type
     * @param {number} spa_id Player account ID
     * @param {string} [lang] Response language
     * @param {number} [page] Page number
     * @param {number} [page_size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPlayerAchievementsRaw(requestParameters: GetPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPlayerAchievements200Response>>;

    /**
     * Returns personal and common achievement statistics for a user.
     * Search achievements by user
     */
    getPlayerAchievements(requestParameters: GetPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPlayerAchievements200Response>;

    /**
     * Returns full player tank achievements for the Hall of Fame.
     * @summary Player tank achievements
     * @param {number} vehicle_cd Vehicle ID
     * @param {number} battles_count Minimum number of battles
     * @param {string} time_slice Period (YYYY-MM)
     * @param {string} stat_type Statistic type
     * @param {number} spa_id Player account ID
     * @param {string} [lang] Response language
     * @param {number} [page] Page number
     * @param {number} [page_size] Number of items per page
     * @param {string} [social_slice] Social filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPlayerTankAchievementsRaw(requestParameters: GetPlayerTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPlayerTankAchievements200Response>>;

    /**
     * Returns full player tank achievements for the Hall of Fame.
     * Player tank achievements
     */
    getPlayerTankAchievements(requestParameters: GetPlayerTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPlayerTankAchievements200Response>;

    /**
     * Returns list of vehicles.
     * @summary Get Hall of Fame Tanks
     * @param {string} filter_language Response language
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getVehiclesRaw(requestParameters: GetVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVehicles200Response>>;

    /**
     * Returns list of vehicles.
     * Get Hall of Fame Tanks
     */
    getVehicles(requestParameters: GetVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVehicles200Response>;

    /**
     * Returns search results for clans and players.
     * @summary Extended search for players and clans
     * @param {string} search_str Search string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    searchPlayersAndClansRaw(requestParameters: SearchPlayersAndClansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchPlayersAndClans200Response>>;

    /**
     * Returns search results for clans and players.
     * Extended search for players and clans
     */
    searchPlayersAndClans(requestParameters: SearchPlayersAndClansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchPlayersAndClans200Response>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Returns full player statistics for the Hall of Fame.
     * Get Hall of Fame achievements
     */
    async getHallOfFameAchievementsRaw(requestParameters: GetHallOfFameAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHallOfFameAchievements200Response>> {
        if (requestParameters['battles_count'] == null) {
            throw new runtime.RequiredError(
                'battles_count',
                'Required parameter "battles_count" was null or undefined when calling getHallOfFameAchievements().'
            );
        }

        if (requestParameters['tier_group'] == null) {
            throw new runtime.RequiredError(
                'tier_group',
                'Required parameter "tier_group" was null or undefined when calling getHallOfFameAchievements().'
            );
        }

        if (requestParameters['time_slice'] == null) {
            throw new runtime.RequiredError(
                'time_slice',
                'Required parameter "time_slice" was null or undefined when calling getHallOfFameAchievements().'
            );
        }

        if (requestParameters['stat_type'] == null) {
            throw new runtime.RequiredError(
                'stat_type',
                'Required parameter "stat_type" was null or undefined when calling getHallOfFameAchievements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['battles_count'] != null) {
            queryParameters['battles_count'] = requestParameters['battles_count'];
        }

        if (requestParameters['tier_group'] != null) {
            queryParameters['tier_group'] = requestParameters['tier_group'];
        }

        if (requestParameters['time_slice'] != null) {
            queryParameters['time_slice'] = requestParameters['time_slice'];
        }

        if (requestParameters['stat_type'] != null) {
            queryParameters['stat_type'] = requestParameters['stat_type'];
        }

        if (requestParameters['social_slice'] != null) {
            queryParameters['social_slice'] = requestParameters['social_slice'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/achievements/full/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHallOfFameAchievements200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns full player statistics for the Hall of Fame.
     * Get Hall of Fame achievements
     */
    async getHallOfFameAchievements(requestParameters: GetHallOfFameAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHallOfFameAchievements200Response> {
        const response = await this.getHallOfFameAchievementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns full player tank statistics for the Hall of Fame.
     * Get Hall of Fame Tank achievements
     */
    async getHallOfFameTankAchievementsRaw(requestParameters: GetHallOfFameTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHallOfFameTankAchievements200Response>> {
        if (requestParameters['vehicle_cd'] == null) {
            throw new runtime.RequiredError(
                'vehicle_cd',
                'Required parameter "vehicle_cd" was null or undefined when calling getHallOfFameTankAchievements().'
            );
        }

        if (requestParameters['battles_count'] == null) {
            throw new runtime.RequiredError(
                'battles_count',
                'Required parameter "battles_count" was null or undefined when calling getHallOfFameTankAchievements().'
            );
        }

        if (requestParameters['time_slice'] == null) {
            throw new runtime.RequiredError(
                'time_slice',
                'Required parameter "time_slice" was null or undefined when calling getHallOfFameTankAchievements().'
            );
        }

        if (requestParameters['stat_type'] == null) {
            throw new runtime.RequiredError(
                'stat_type',
                'Required parameter "stat_type" was null or undefined when calling getHallOfFameTankAchievements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['battles_count'] != null) {
            queryParameters['battles_count'] = requestParameters['battles_count'];
        }

        if (requestParameters['time_slice'] != null) {
            queryParameters['time_slice'] = requestParameters['time_slice'];
        }

        if (requestParameters['stat_type'] != null) {
            queryParameters['stat_type'] = requestParameters['stat_type'];
        }

        if (requestParameters['social_slice'] != null) {
            queryParameters['social_slice'] = requestParameters['social_slice'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vehicles/{vehicle_cd}/`;
        urlPath = urlPath.replace(`{${"vehicle_cd"}}`, encodeURIComponent(String(requestParameters['vehicle_cd'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHallOfFameTankAchievements200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns full player tank statistics for the Hall of Fame.
     * Get Hall of Fame Tank achievements
     */
    async getHallOfFameTankAchievements(requestParameters: GetHallOfFameTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHallOfFameTankAchievements200Response> {
        const response = await this.getHallOfFameTankAchievementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns personal and common achievement statistics for a user.
     * Search achievements by user
     */
    async getPlayerAchievementsRaw(requestParameters: GetPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPlayerAchievements200Response>> {
        if (requestParameters['battles_count'] == null) {
            throw new runtime.RequiredError(
                'battles_count',
                'Required parameter "battles_count" was null or undefined when calling getPlayerAchievements().'
            );
        }

        if (requestParameters['tier_group'] == null) {
            throw new runtime.RequiredError(
                'tier_group',
                'Required parameter "tier_group" was null or undefined when calling getPlayerAchievements().'
            );
        }

        if (requestParameters['time_slice'] == null) {
            throw new runtime.RequiredError(
                'time_slice',
                'Required parameter "time_slice" was null or undefined when calling getPlayerAchievements().'
            );
        }

        if (requestParameters['stat_type'] == null) {
            throw new runtime.RequiredError(
                'stat_type',
                'Required parameter "stat_type" was null or undefined when calling getPlayerAchievements().'
            );
        }

        if (requestParameters['spa_id'] == null) {
            throw new runtime.RequiredError(
                'spa_id',
                'Required parameter "spa_id" was null or undefined when calling getPlayerAchievements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['battles_count'] != null) {
            queryParameters['battles_count'] = requestParameters['battles_count'];
        }

        if (requestParameters['tier_group'] != null) {
            queryParameters['tier_group'] = requestParameters['tier_group'];
        }

        if (requestParameters['time_slice'] != null) {
            queryParameters['time_slice'] = requestParameters['time_slice'];
        }

        if (requestParameters['stat_type'] != null) {
            queryParameters['stat_type'] = requestParameters['stat_type'];
        }

        if (requestParameters['spa_id'] != null) {
            queryParameters['spa_id'] = requestParameters['spa_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/achievements/search/by_user/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPlayerAchievements200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns personal and common achievement statistics for a user.
     * Search achievements by user
     */
    async getPlayerAchievements(requestParameters: GetPlayerAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPlayerAchievements200Response> {
        const response = await this.getPlayerAchievementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns full player tank achievements for the Hall of Fame.
     * Player tank achievements
     */
    async getPlayerTankAchievementsRaw(requestParameters: GetPlayerTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPlayerTankAchievements200Response>> {
        if (requestParameters['vehicle_cd'] == null) {
            throw new runtime.RequiredError(
                'vehicle_cd',
                'Required parameter "vehicle_cd" was null or undefined when calling getPlayerTankAchievements().'
            );
        }

        if (requestParameters['battles_count'] == null) {
            throw new runtime.RequiredError(
                'battles_count',
                'Required parameter "battles_count" was null or undefined when calling getPlayerTankAchievements().'
            );
        }

        if (requestParameters['time_slice'] == null) {
            throw new runtime.RequiredError(
                'time_slice',
                'Required parameter "time_slice" was null or undefined when calling getPlayerTankAchievements().'
            );
        }

        if (requestParameters['stat_type'] == null) {
            throw new runtime.RequiredError(
                'stat_type',
                'Required parameter "stat_type" was null or undefined when calling getPlayerTankAchievements().'
            );
        }

        if (requestParameters['spa_id'] == null) {
            throw new runtime.RequiredError(
                'spa_id',
                'Required parameter "spa_id" was null or undefined when calling getPlayerTankAchievements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['battles_count'] != null) {
            queryParameters['battles_count'] = requestParameters['battles_count'];
        }

        if (requestParameters['time_slice'] != null) {
            queryParameters['time_slice'] = requestParameters['time_slice'];
        }

        if (requestParameters['stat_type'] != null) {
            queryParameters['stat_type'] = requestParameters['stat_type'];
        }

        if (requestParameters['social_slice'] != null) {
            queryParameters['social_slice'] = requestParameters['social_slice'];
        }

        if (requestParameters['spa_id'] != null) {
            queryParameters['spa_id'] = requestParameters['spa_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vehicles/{vehicle_cd}/search/by_user/`;
        urlPath = urlPath.replace(`{${"vehicle_cd"}}`, encodeURIComponent(String(requestParameters['vehicle_cd'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPlayerTankAchievements200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns full player tank achievements for the Hall of Fame.
     * Player tank achievements
     */
    async getPlayerTankAchievements(requestParameters: GetPlayerTankAchievementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPlayerTankAchievements200Response> {
        const response = await this.getPlayerTankAchievementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns list of vehicles.
     * Get Hall of Fame Tanks
     */
    async getVehiclesRaw(requestParameters: GetVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVehicles200Response>> {
        if (requestParameters['filter_language'] == null) {
            throw new runtime.RequiredError(
                'filter_language',
                'Required parameter "filter_language" was null or undefined when calling getVehicles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter_language'] != null) {
            queryParameters['filter[language]'] = requestParameters['filter_language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/vehicles/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVehicles200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns list of vehicles.
     * Get Hall of Fame Tanks
     */
    async getVehicles(requestParameters: GetVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVehicles200Response> {
        const response = await this.getVehiclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns search results for clans and players.
     * Extended search for players and clans
     */
    async searchPlayersAndClansRaw(requestParameters: SearchPlayersAndClansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchPlayersAndClans200Response>> {
        if (requestParameters['search_str'] == null) {
            throw new runtime.RequiredError(
                'search_str',
                'Required parameter "search_str" was null or undefined when calling searchPlayersAndClans().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search_str'] != null) {
            queryParameters['search_str'] = requestParameters['search_str'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchPlayersAndClans200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns search results for clans and players.
     * Extended search for players and clans
     */
    async searchPlayersAndClans(requestParameters: SearchPlayersAndClansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchPlayersAndClans200Response> {
        const response = await this.searchPlayersAndClansRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
