/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { AchievementsData } from './AchievementsData.js';
import {
    AchievementsDataFromJSON,
    AchievementsDataFromJSONTyped,
    AchievementsDataToJSON,
    AchievementsDataToJSONTyped,
} from './AchievementsData.js';

/**
 * 
 * @export
 * @interface AchievementsResponse
 */
export interface AchievementsResponse {
    /**
     * 
     * @type {Meta}
     * @memberof AchievementsResponse
     */
    meta?: Meta;
    /**
     * 
     * @type {AchievementsData}
     * @memberof AchievementsResponse
     */
    data?: AchievementsData;
    /**
     * 
     * @type {string}
     * @memberof AchievementsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AchievementsResponse interface.
 */
export function instanceOfAchievementsResponse(value: object): value is AchievementsResponse {
    return true;
}

export function AchievementsResponseFromJSON(json: any): AchievementsResponse {
    return AchievementsResponseFromJSONTyped(json, false);
}

export function AchievementsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : AchievementsDataFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AchievementsResponseToJSON(json: any): AchievementsResponse {
    return AchievementsResponseToJSONTyped(json, false);
}

export function AchievementsResponseToJSONTyped(value?: AchievementsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
        'data': AchievementsDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const AchievementsResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

