/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PlayerStats } from './PlayerStats.js';
import {
    PlayerStatsFromJSON,
    PlayerStatsFromJSONTyped,
    PlayerStatsToJSON,
    PlayerStatsToJSONTyped,
} from './PlayerStats.js';

/**
 * 
 * @export
 * @interface AchievementsData
 */
export interface AchievementsData {
    /**
     * 
     * @type {object}
     * @memberof AchievementsData
     */
    personal: object;
    /**
     * 
     * @type {Array<PlayerStats>}
     * @memberof AchievementsData
     */
    common: Array<PlayerStats>;
}

/**
 * Check if a given object implements the AchievementsData interface.
 */
export function instanceOfAchievementsData(value: object): value is AchievementsData {
    if (!('personal' in value) || value['personal'] === undefined) return false;
    if (!('common' in value) || value['common'] === undefined) return false;
    return true;
}

export function AchievementsDataFromJSON(json: any): AchievementsData {
    return AchievementsDataFromJSONTyped(json, false);
}

export function AchievementsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AchievementsData {
    if (json == null) {
        return json;
    }
    return {
        
        'personal': json['personal'],
        'common': ((json['common'] as Array<any>).map(PlayerStatsFromJSON)),
    };
}

export function AchievementsDataToJSON(json: any): AchievementsData {
    return AchievementsDataToJSONTyped(json, false);
}

export function AchievementsDataToJSONTyped(value?: AchievementsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personal': value['personal'],
        'common': ((value['common'] as Array<any>).map(PlayerStatsToJSON)),
    };
}

export const AchievementsDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

