/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ClanInfo
 */
export interface ClanInfo {
    /**
     * 
     * @type {string}
     * @memberof ClanInfo
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof ClanInfo
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof ClanInfo
     */
    id: number;
}

/**
 * Check if a given object implements the ClanInfo interface.
 */
export function instanceOfClanInfo(value: object): value is ClanInfo {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ClanInfoFromJSON(json: any): ClanInfo {
    return ClanInfoFromJSONTyped(json, false);
}

export function ClanInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClanInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'color': json['color'],
        'id': json['id'],
    };
}

export function ClanInfoToJSON(json: any): ClanInfo {
    return ClanInfoToJSONTyped(json, false);
}

export function ClanInfoToJSONTyped(value?: ClanInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'color': value['color'],
        'id': value['id'],
    };
}

export const ClanInfoPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

