/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { TankAchievementsData } from './TankAchievementsData.js';
import {
    TankAchievementsDataFromJSON,
    TankAchievementsDataFromJSONTyped,
    TankAchievementsDataToJSON,
    TankAchievementsDataToJSONTyped,
} from './TankAchievementsData.js';

/**
 * 
 * @export
 * @interface GetHallOfFameTankAchievements200Response
 */
export interface GetHallOfFameTankAchievements200Response {
    /**
     * 
     * @type {Meta}
     * @memberof GetHallOfFameTankAchievements200Response
     */
    meta: Meta;
    /**
     * 
     * @type {TankAchievementsData}
     * @memberof GetHallOfFameTankAchievements200Response
     */
    data: TankAchievementsData;
    /**
     * 
     * @type {string}
     * @memberof GetHallOfFameTankAchievements200Response
     */
    status: string;
}

/**
 * Check if a given object implements the GetHallOfFameTankAchievements200Response interface.
 */
export function instanceOfGetHallOfFameTankAchievements200Response(value: object): value is GetHallOfFameTankAchievements200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetHallOfFameTankAchievements200ResponseFromJSON(json: any): GetHallOfFameTankAchievements200Response {
    return GetHallOfFameTankAchievements200ResponseFromJSONTyped(json, false);
}

export function GetHallOfFameTankAchievements200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHallOfFameTankAchievements200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MetaFromJSON(json['meta']),
        'data': TankAchievementsDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function GetHallOfFameTankAchievements200ResponseToJSON(json: any): GetHallOfFameTankAchievements200Response {
    return GetHallOfFameTankAchievements200ResponseToJSONTyped(json, false);
}

export function GetHallOfFameTankAchievements200ResponseToJSONTyped(value?: GetHallOfFameTankAchievements200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
        'data': TankAchievementsDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const GetHallOfFameTankAchievements200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

