/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { AchievementsData } from './AchievementsData.js';
import {
    AchievementsDataFromJSON,
    AchievementsDataFromJSONTyped,
    AchievementsDataToJSON,
    AchievementsDataToJSONTyped,
} from './AchievementsData.js';

/**
 * 
 * @export
 * @interface GetHallOfFameAchivements200Response
 */
export interface GetHallOfFameAchivements200Response {
    /**
     * 
     * @type {Meta}
     * @memberof GetHallOfFameAchivements200Response
     */
    meta: Meta;
    /**
     * 
     * @type {AchievementsData}
     * @memberof GetHallOfFameAchivements200Response
     */
    data: AchievementsData;
    /**
     * 
     * @type {string}
     * @memberof GetHallOfFameAchivements200Response
     */
    status: string;
}

/**
 * Check if a given object implements the GetHallOfFameAchivements200Response interface.
 */
export function instanceOfGetHallOfFameAchivements200Response(value: object): value is GetHallOfFameAchivements200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetHallOfFameAchivements200ResponseFromJSON(json: any): GetHallOfFameAchivements200Response {
    return GetHallOfFameAchivements200ResponseFromJSONTyped(json, false);
}

export function GetHallOfFameAchivements200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHallOfFameAchivements200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MetaFromJSON(json['meta']),
        'data': AchievementsDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function GetHallOfFameAchivements200ResponseToJSON(json: any): GetHallOfFameAchivements200Response {
    return GetHallOfFameAchivements200ResponseToJSONTyped(json, false);
}

export function GetHallOfFameAchivements200ResponseToJSONTyped(value?: GetHallOfFameAchivements200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
        'data': AchievementsDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const GetHallOfFameAchivements200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

