/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PlayerStats } from './PlayerStats.js';
import {
    PlayerStatsFromJSON,
    PlayerStatsFromJSONTyped,
    PlayerStatsToJSON,
    PlayerStatsToJSONTyped,
} from './PlayerStats.js';
import type { GetPlayerTankAchievements200ResponseDataExtra } from './GetPlayerTankAchievements200ResponseDataExtra.js';
import {
    GetPlayerTankAchievements200ResponseDataExtraFromJSON,
    GetPlayerTankAchievements200ResponseDataExtraFromJSONTyped,
    GetPlayerTankAchievements200ResponseDataExtraToJSON,
    GetPlayerTankAchievements200ResponseDataExtraToJSONTyped,
} from './GetPlayerTankAchievements200ResponseDataExtra.js';

/**
 * 
 * @export
 * @interface GetPlayerTankAchievements200ResponseData
 */
export interface GetPlayerTankAchievements200ResponseData {
    /**
     * 
     * @type {Array<PlayerStats>}
     * @memberof GetPlayerTankAchievements200ResponseData
     */
    players: Array<PlayerStats>;
    /**
     * 
     * @type {GetPlayerTankAchievements200ResponseDataExtra}
     * @memberof GetPlayerTankAchievements200ResponseData
     */
    extra: GetPlayerTankAchievements200ResponseDataExtra;
}

/**
 * Check if a given object implements the GetPlayerTankAchievements200ResponseData interface.
 */
export function instanceOfGetPlayerTankAchievements200ResponseData(value: object): value is GetPlayerTankAchievements200ResponseData {
    if (!('players' in value) || value['players'] === undefined) return false;
    if (!('extra' in value) || value['extra'] === undefined) return false;
    return true;
}

export function GetPlayerTankAchievements200ResponseDataFromJSON(json: any): GetPlayerTankAchievements200ResponseData {
    return GetPlayerTankAchievements200ResponseDataFromJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerTankAchievements200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(PlayerStatsFromJSON)),
        'extra': GetPlayerTankAchievements200ResponseDataExtraFromJSON(json['extra']),
    };
}

export function GetPlayerTankAchievements200ResponseDataToJSON(json: any): GetPlayerTankAchievements200ResponseData {
    return GetPlayerTankAchievements200ResponseDataToJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseDataToJSONTyped(value?: GetPlayerTankAchievements200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': ((value['players'] as Array<any>).map(PlayerStatsToJSON)),
        'extra': GetPlayerTankAchievements200ResponseDataExtraToJSON(value['extra']),
    };
}

export const GetPlayerTankAchievements200ResponseDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

