/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPlayerAchievements200ResponseDataPersonalClanInfo } from './GetPlayerAchievements200ResponseDataPersonalClanInfo.js';
import {
    GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSON,
    GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSONTyped,
    GetPlayerAchievements200ResponseDataPersonalClanInfoToJSON,
    GetPlayerAchievements200ResponseDataPersonalClanInfoToJSONTyped,
} from './GetPlayerAchievements200ResponseDataPersonalClanInfo.js';

/**
 * 
 * @export
 * @interface GetPlayerAchievements200ResponseDataPersonal
 */
export interface GetPlayerAchievements200ResponseDataPersonal {
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    destruction_ratio: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_assisted_avg_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_dealt_avg_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_dealt_avg: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_blocked_avg_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    win_rate_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    battles_count: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    sbr: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    position_delta: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    average_level: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    sbr_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    date_before: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    account_id: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    date: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    frags_avg_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    battles_count_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    frags_avg: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_blocked_avg: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    base_capture_points: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    xp_avg_delta: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    survability: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_assisted_avg: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    position: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    win_rate: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    damage_ratio: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    base_defense_points: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    hits_percent: number;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    enemy_vehicles_spotted_avg: number;
    /**
     * 
     * @type {GetPlayerAchievements200ResponseDataPersonalClanInfo}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    clan_info: GetPlayerAchievements200ResponseDataPersonalClanInfo;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonal
     */
    xp_avg: number;
}

/**
 * Check if a given object implements the GetPlayerAchievements200ResponseDataPersonal interface.
 */
export function instanceOfGetPlayerAchievements200ResponseDataPersonal(value: object): value is GetPlayerAchievements200ResponseDataPersonal {
    if (!('destruction_ratio' in value) || value['destruction_ratio'] === undefined) return false;
    if (!('damage_assisted_avg_delta' in value) || value['damage_assisted_avg_delta'] === undefined) return false;
    if (!('damage_dealt_avg_delta' in value) || value['damage_dealt_avg_delta'] === undefined) return false;
    if (!('damage_dealt_avg' in value) || value['damage_dealt_avg'] === undefined) return false;
    if (!('damage_blocked_avg_delta' in value) || value['damage_blocked_avg_delta'] === undefined) return false;
    if (!('win_rate_delta' in value) || value['win_rate_delta'] === undefined) return false;
    if (!('battles_count' in value) || value['battles_count'] === undefined) return false;
    if (!('sbr' in value) || value['sbr'] === undefined) return false;
    if (!('position_delta' in value) || value['position_delta'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('average_level' in value) || value['average_level'] === undefined) return false;
    if (!('sbr_delta' in value) || value['sbr_delta'] === undefined) return false;
    if (!('date_before' in value) || value['date_before'] === undefined) return false;
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('frags_avg_delta' in value) || value['frags_avg_delta'] === undefined) return false;
    if (!('battles_count_delta' in value) || value['battles_count_delta'] === undefined) return false;
    if (!('frags_avg' in value) || value['frags_avg'] === undefined) return false;
    if (!('damage_blocked_avg' in value) || value['damage_blocked_avg'] === undefined) return false;
    if (!('base_capture_points' in value) || value['base_capture_points'] === undefined) return false;
    if (!('xp_avg_delta' in value) || value['xp_avg_delta'] === undefined) return false;
    if (!('survability' in value) || value['survability'] === undefined) return false;
    if (!('damage_assisted_avg' in value) || value['damage_assisted_avg'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('win_rate' in value) || value['win_rate'] === undefined) return false;
    if (!('damage_ratio' in value) || value['damage_ratio'] === undefined) return false;
    if (!('base_defense_points' in value) || value['base_defense_points'] === undefined) return false;
    if (!('hits_percent' in value) || value['hits_percent'] === undefined) return false;
    if (!('enemy_vehicles_spotted_avg' in value) || value['enemy_vehicles_spotted_avg'] === undefined) return false;
    if (!('clan_info' in value) || value['clan_info'] === undefined) return false;
    if (!('xp_avg' in value) || value['xp_avg'] === undefined) return false;
    return true;
}

export function GetPlayerAchievements200ResponseDataPersonalFromJSON(json: any): GetPlayerAchievements200ResponseDataPersonal {
    return GetPlayerAchievements200ResponseDataPersonalFromJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataPersonalFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerAchievements200ResponseDataPersonal {
    if (json == null) {
        return json;
    }
    return {
        
        'destruction_ratio': json['destruction_ratio'],
        'damage_assisted_avg_delta': json['damage_assisted_avg_delta'],
        'damage_dealt_avg_delta': json['damage_dealt_avg_delta'],
        'damage_dealt_avg': json['damage_dealt_avg'],
        'damage_blocked_avg_delta': json['damage_blocked_avg_delta'],
        'win_rate_delta': json['win_rate_delta'],
        'battles_count': json['battles_count'],
        'sbr': json['sbr'],
        'position_delta': json['position_delta'],
        'nickname': json['nickname'],
        'average_level': json['average_level'],
        'sbr_delta': json['sbr_delta'],
        'date_before': json['date_before'],
        'account_id': json['account_id'],
        'date': json['date'],
        'frags_avg_delta': json['frags_avg_delta'],
        'battles_count_delta': json['battles_count_delta'],
        'frags_avg': json['frags_avg'],
        'damage_blocked_avg': json['damage_blocked_avg'],
        'base_capture_points': json['base_capture_points'],
        'xp_avg_delta': json['xp_avg_delta'],
        'survability': json['survability'],
        'damage_assisted_avg': json['damage_assisted_avg'],
        'position': json['position'],
        'win_rate': json['win_rate'],
        'damage_ratio': json['damage_ratio'],
        'base_defense_points': json['base_defense_points'],
        'hits_percent': json['hits_percent'],
        'enemy_vehicles_spotted_avg': json['enemy_vehicles_spotted_avg'],
        'clan_info': GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSON(json['clan_info']),
        'xp_avg': json['xp_avg'],
    };
}

export function GetPlayerAchievements200ResponseDataPersonalToJSON(json: any): GetPlayerAchievements200ResponseDataPersonal {
    return GetPlayerAchievements200ResponseDataPersonalToJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataPersonalToJSONTyped(value?: GetPlayerAchievements200ResponseDataPersonal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destruction_ratio': value['destruction_ratio'],
        'damage_assisted_avg_delta': value['damage_assisted_avg_delta'],
        'damage_dealt_avg_delta': value['damage_dealt_avg_delta'],
        'damage_dealt_avg': value['damage_dealt_avg'],
        'damage_blocked_avg_delta': value['damage_blocked_avg_delta'],
        'win_rate_delta': value['win_rate_delta'],
        'battles_count': value['battles_count'],
        'sbr': value['sbr'],
        'position_delta': value['position_delta'],
        'nickname': value['nickname'],
        'average_level': value['average_level'],
        'sbr_delta': value['sbr_delta'],
        'date_before': value['date_before'],
        'account_id': value['account_id'],
        'date': value['date'],
        'frags_avg_delta': value['frags_avg_delta'],
        'battles_count_delta': value['battles_count_delta'],
        'frags_avg': value['frags_avg'],
        'damage_blocked_avg': value['damage_blocked_avg'],
        'base_capture_points': value['base_capture_points'],
        'xp_avg_delta': value['xp_avg_delta'],
        'survability': value['survability'],
        'damage_assisted_avg': value['damage_assisted_avg'],
        'position': value['position'],
        'win_rate': value['win_rate'],
        'damage_ratio': value['damage_ratio'],
        'base_defense_points': value['base_defense_points'],
        'hits_percent': value['hits_percent'],
        'enemy_vehicles_spotted_avg': value['enemy_vehicles_spotted_avg'],
        'clan_info': GetPlayerAchievements200ResponseDataPersonalClanInfoToJSON(value['clan_info']),
        'xp_avg': value['xp_avg'],
    };
}

export const GetPlayerAchievements200ResponseDataPersonalPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

