/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PlayerStats } from './PlayerStats.js';
import {
    PlayerStatsFromJSON,
    PlayerStatsFromJSONTyped,
    PlayerStatsToJSON,
    PlayerStatsToJSONTyped,
} from './PlayerStats.js';

/**
 * 
 * @export
 * @interface GetPlayerTankAchievements200ResponseDataExtra
 */
export interface GetPlayerTankAchievements200ResponseDataExtra {
    /**
     * 
     * @type {PlayerStats}
     * @memberof GetPlayerTankAchievements200ResponseDataExtra
     */
    data?: PlayerStats;
}

/**
 * Check if a given object implements the GetPlayerTankAchievements200ResponseDataExtra interface.
 */
export function instanceOfGetPlayerTankAchievements200ResponseDataExtra(value: object): value is GetPlayerTankAchievements200ResponseDataExtra {
    return true;
}

export function GetPlayerTankAchievements200ResponseDataExtraFromJSON(json: any): GetPlayerTankAchievements200ResponseDataExtra {
    return GetPlayerTankAchievements200ResponseDataExtraFromJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseDataExtraFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerTankAchievements200ResponseDataExtra {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PlayerStatsFromJSON(json['data']),
    };
}

export function GetPlayerTankAchievements200ResponseDataExtraToJSON(json: any): GetPlayerTankAchievements200ResponseDataExtra {
    return GetPlayerTankAchievements200ResponseDataExtraToJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseDataExtraToJSONTyped(value?: GetPlayerTankAchievements200ResponseDataExtra | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PlayerStatsToJSON(value['data']),
    };
}

export const GetPlayerTankAchievements200ResponseDataExtraPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

