/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPlayerAchievements200ResponseData } from './GetPlayerAchievements200ResponseData.js';
import {
    GetPlayerAchievements200ResponseDataFromJSON,
    GetPlayerAchievements200ResponseDataFromJSONTyped,
    GetPlayerAchievements200ResponseDataToJSON,
    GetPlayerAchievements200ResponseDataToJSONTyped,
} from './GetPlayerAchievements200ResponseData.js';
import type { GetPlayerAchievements200ResponseMeta } from './GetPlayerAchievements200ResponseMeta.js';
import {
    GetPlayerAchievements200ResponseMetaFromJSON,
    GetPlayerAchievements200ResponseMetaFromJSONTyped,
    GetPlayerAchievements200ResponseMetaToJSON,
    GetPlayerAchievements200ResponseMetaToJSONTyped,
} from './GetPlayerAchievements200ResponseMeta.js';

/**
 * 
 * @export
 * @interface GetPlayerAchievements200Response
 */
export interface GetPlayerAchievements200Response {
    /**
     * 
     * @type {GetPlayerAchievements200ResponseMeta}
     * @memberof GetPlayerAchievements200Response
     */
    meta: GetPlayerAchievements200ResponseMeta;
    /**
     * 
     * @type {GetPlayerAchievements200ResponseData}
     * @memberof GetPlayerAchievements200Response
     */
    data: GetPlayerAchievements200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof GetPlayerAchievements200Response
     */
    status: string;
}

/**
 * Check if a given object implements the GetPlayerAchievements200Response interface.
 */
export function instanceOfGetPlayerAchievements200Response(value: object): value is GetPlayerAchievements200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetPlayerAchievements200ResponseFromJSON(json: any): GetPlayerAchievements200Response {
    return GetPlayerAchievements200ResponseFromJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerAchievements200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': GetPlayerAchievements200ResponseMetaFromJSON(json['meta']),
        'data': GetPlayerAchievements200ResponseDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function GetPlayerAchievements200ResponseToJSON(json: any): GetPlayerAchievements200Response {
    return GetPlayerAchievements200ResponseToJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseToJSONTyped(value?: GetPlayerAchievements200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': GetPlayerAchievements200ResponseMetaToJSON(value['meta']),
        'data': GetPlayerAchievements200ResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const GetPlayerAchievements200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

