/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPlayerAchievements200ResponseDataPersonal } from './GetPlayerAchievements200ResponseDataPersonal.js';
import {
    GetPlayerAchievements200ResponseDataPersonalFromJSON,
    GetPlayerAchievements200ResponseDataPersonalFromJSONTyped,
    GetPlayerAchievements200ResponseDataPersonalToJSON,
    GetPlayerAchievements200ResponseDataPersonalToJSONTyped,
} from './GetPlayerAchievements200ResponseDataPersonal.js';

/**
 * 
 * @export
 * @interface GetPlayerAchievements200ResponseData
 */
export interface GetPlayerAchievements200ResponseData {
    /**
     * 
     * @type {GetPlayerAchievements200ResponseDataPersonal}
     * @memberof GetPlayerAchievements200ResponseData
     */
    personal: GetPlayerAchievements200ResponseDataPersonal;
    /**
     * 
     * @type {Array<GetPlayerAchievements200ResponseDataPersonal>}
     * @memberof GetPlayerAchievements200ResponseData
     */
    common: Array<GetPlayerAchievements200ResponseDataPersonal>;
}

/**
 * Check if a given object implements the GetPlayerAchievements200ResponseData interface.
 */
export function instanceOfGetPlayerAchievements200ResponseData(value: object): value is GetPlayerAchievements200ResponseData {
    if (!('personal' in value) || value['personal'] === undefined) return false;
    if (!('common' in value) || value['common'] === undefined) return false;
    return true;
}

export function GetPlayerAchievements200ResponseDataFromJSON(json: any): GetPlayerAchievements200ResponseData {
    return GetPlayerAchievements200ResponseDataFromJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerAchievements200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'personal': GetPlayerAchievements200ResponseDataPersonalFromJSON(json['personal']),
        'common': ((json['common'] as Array<any>).map(GetPlayerAchievements200ResponseDataPersonalFromJSON)),
    };
}

export function GetPlayerAchievements200ResponseDataToJSON(json: any): GetPlayerAchievements200ResponseData {
    return GetPlayerAchievements200ResponseDataToJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataToJSONTyped(value?: GetPlayerAchievements200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personal': GetPlayerAchievements200ResponseDataPersonalToJSON(value['personal']),
        'common': ((value['common'] as Array<any>).map(GetPlayerAchievements200ResponseDataPersonalToJSON)),
    };
}

export const GetPlayerAchievements200ResponseDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

