/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetPlayerAchievements200ResponseDataPersonalClanInfo
 */
export interface GetPlayerAchievements200ResponseDataPersonalClanInfo {
    /**
     * 
     * @type {string}
     * @memberof GetPlayerAchievements200ResponseDataPersonalClanInfo
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof GetPlayerAchievements200ResponseDataPersonalClanInfo
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof GetPlayerAchievements200ResponseDataPersonalClanInfo
     */
    id: number;
}

/**
 * Check if a given object implements the GetPlayerAchievements200ResponseDataPersonalClanInfo interface.
 */
export function instanceOfGetPlayerAchievements200ResponseDataPersonalClanInfo(value: object): value is GetPlayerAchievements200ResponseDataPersonalClanInfo {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSON(json: any): GetPlayerAchievements200ResponseDataPersonalClanInfo {
    return GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataPersonalClanInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerAchievements200ResponseDataPersonalClanInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'color': json['color'],
        'id': json['id'],
    };
}

export function GetPlayerAchievements200ResponseDataPersonalClanInfoToJSON(json: any): GetPlayerAchievements200ResponseDataPersonalClanInfo {
    return GetPlayerAchievements200ResponseDataPersonalClanInfoToJSONTyped(json, false);
}

export function GetPlayerAchievements200ResponseDataPersonalClanInfoToJSONTyped(value?: GetPlayerAchievements200ResponseDataPersonalClanInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'color': value['color'],
        'id': value['id'],
    };
}

export const GetPlayerAchievements200ResponseDataPersonalClanInfoPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

