/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { GetPlayerTankAchievements200ResponseData } from './GetPlayerTankAchievements200ResponseData.js';
import {
    GetPlayerTankAchievements200ResponseDataFromJSON,
    GetPlayerTankAchievements200ResponseDataFromJSONTyped,
    GetPlayerTankAchievements200ResponseDataToJSON,
    GetPlayerTankAchievements200ResponseDataToJSONTyped,
} from './GetPlayerTankAchievements200ResponseData.js';

/**
 * 
 * @export
 * @interface GetPlayerTankAchievements200Response
 */
export interface GetPlayerTankAchievements200Response {
    /**
     * 
     * @type {Meta}
     * @memberof GetPlayerTankAchievements200Response
     */
    meta: Meta;
    /**
     * 
     * @type {GetPlayerTankAchievements200ResponseData}
     * @memberof GetPlayerTankAchievements200Response
     */
    data: GetPlayerTankAchievements200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof GetPlayerTankAchievements200Response
     */
    status: string;
}

/**
 * Check if a given object implements the GetPlayerTankAchievements200Response interface.
 */
export function instanceOfGetPlayerTankAchievements200Response(value: object): value is GetPlayerTankAchievements200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetPlayerTankAchievements200ResponseFromJSON(json: any): GetPlayerTankAchievements200Response {
    return GetPlayerTankAchievements200ResponseFromJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerTankAchievements200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MetaFromJSON(json['meta']),
        'data': GetPlayerTankAchievements200ResponseDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function GetPlayerTankAchievements200ResponseToJSON(json: any): GetPlayerTankAchievements200Response {
    return GetPlayerTankAchievements200ResponseToJSONTyped(json, false);
}

export function GetPlayerTankAchievements200ResponseToJSONTyped(value?: GetPlayerTankAchievements200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
        'data': GetPlayerTankAchievements200ResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const GetPlayerTankAchievements200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

