/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
 */
export interface GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner {
    /**
     * 
     * @type {boolean}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    premium: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    nation: string;
    /**
     * 
     * @type {number}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    vehicle_cd: number;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    role: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    collector_vehicle: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    tier: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    tank_nations_list: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    short_mark: string;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    tech_name: string;
    /**
     * 
     * @type {number}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    default_icon: number;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner
     */
    default_image: number;
}

/**
 * Check if a given object implements the GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner interface.
 */
export function instanceOfGetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner(value: object): value is GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner {
    if (!('premium' in value) || value['premium'] === undefined) return false;
    if (!('nation' in value) || value['nation'] === undefined) return false;
    if (!('vehicle_cd' in value) || value['vehicle_cd'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('collector_vehicle' in value) || value['collector_vehicle'] === undefined) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('tank_nations_list' in value) || value['tank_nations_list'] === undefined) return false;
    if (!('short_mark' in value) || value['short_mark'] === undefined) return false;
    if (!('tech_name' in value) || value['tech_name'] === undefined) return false;
    if (!('default_icon' in value) || value['default_icon'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('default_image' in value) || value['default_image'] === undefined) return false;
    return true;
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSON(json: any): GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner {
    return GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'premium': json['premium'],
        'nation': json['nation'],
        'vehicle_cd': json['vehicle_cd'],
        'type': json['type'],
        'role': json['role'],
        'collector_vehicle': json['collector_vehicle'],
        'tier': json['tier'],
        'tank_nations_list': json['tank_nations_list'],
        'short_mark': json['short_mark'],
        'tech_name': json['tech_name'],
        'default_icon': json['default_icon'],
        'name': json['name'],
        'default_image': json['default_image'],
    };
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSON(json: any): GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner {
    return GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSONTyped(value?: GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'premium': value['premium'],
        'nation': value['nation'],
        'vehicle_cd': value['vehicle_cd'],
        'type': value['type'],
        'role': value['role'],
        'collector_vehicle': value['collector_vehicle'],
        'tier': value['tier'],
        'tank_nations_list': value['tank_nations_list'],
        'short_mark': value['short_mark'],
        'tech_name': value['tech_name'],
        'default_icon': value['default_icon'],
        'name': value['name'],
        'default_image': value['default_image'],
    };
}

export const GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

