/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetVehicles200ResponseDataNationsInner } from './GetVehicles200ResponseDataNationsInner.js';
import {
    GetVehicles200ResponseDataNationsInnerFromJSON,
    GetVehicles200ResponseDataNationsInnerFromJSONTyped,
    GetVehicles200ResponseDataNationsInnerToJSON,
    GetVehicles200ResponseDataNationsInnerToJSONTyped,
} from './GetVehicles200ResponseDataNationsInner.js';

/**
 * 
 * @export
 * @interface GetVehicles200ResponseData
 */
export interface GetVehicles200ResponseData {
    /**
     * 
     * @type {Array<GetVehicles200ResponseDataNationsInner>}
     * @memberof GetVehicles200ResponseData
     */
    nations: Array<GetVehicles200ResponseDataNationsInner>;
}

/**
 * Check if a given object implements the GetVehicles200ResponseData interface.
 */
export function instanceOfGetVehicles200ResponseData(value: object): value is GetVehicles200ResponseData {
    if (!('nations' in value) || value['nations'] === undefined) return false;
    return true;
}

export function GetVehicles200ResponseDataFromJSON(json: any): GetVehicles200ResponseData {
    return GetVehicles200ResponseDataFromJSONTyped(json, false);
}

export function GetVehicles200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVehicles200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'nations': ((json['nations'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerFromJSON)),
    };
}

export function GetVehicles200ResponseDataToJSON(json: any): GetVehicles200ResponseData {
    return GetVehicles200ResponseDataToJSONTyped(json, false);
}

export function GetVehicles200ResponseDataToJSONTyped(value?: GetVehicles200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nations': ((value['nations'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerToJSON)),
    };
}

export const GetVehicles200ResponseDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

