/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner } from './GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner.js';
import {
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSON,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSONTyped,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSON,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSONTyped,
} from './GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner.js';

/**
 * 
 * @export
 * @interface GetVehicles200ResponseDataNationsInnerVehicleTypesInner
 */
export interface GetVehicles200ResponseDataNationsInnerVehicleTypesInner {
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInner
     */
    vehicleType: string;
    /**
     * 
     * @type {Array<GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner>}
     * @memberof GetVehicles200ResponseDataNationsInnerVehicleTypesInner
     */
    vehicles: Array<GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInner>;
}

/**
 * Check if a given object implements the GetVehicles200ResponseDataNationsInnerVehicleTypesInner interface.
 */
export function instanceOfGetVehicles200ResponseDataNationsInnerVehicleTypesInner(value: object): value is GetVehicles200ResponseDataNationsInnerVehicleTypesInner {
    if (!('vehicleType' in value) || value['vehicleType'] === undefined) return false;
    if (!('vehicles' in value) || value['vehicles'] === undefined) return false;
    return true;
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSON(json: any): GetVehicles200ResponseDataNationsInnerVehicleTypesInner {
    return GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVehicles200ResponseDataNationsInnerVehicleTypesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleType': json['vehicleType'],
        'vehicles': ((json['vehicles'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerFromJSON)),
    };
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSON(json: any): GetVehicles200ResponseDataNationsInnerVehicleTypesInner {
    return GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSONTyped(value?: GetVehicles200ResponseDataNationsInnerVehicleTypesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleType': value['vehicleType'],
        'vehicles': ((value['vehicles'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerVehicleTypesInnerVehiclesInnerToJSON)),
    };
}

export const GetVehicles200ResponseDataNationsInnerVehicleTypesInnerPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

