/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetVehicles200ResponseDataNationsInnerVehicleTypesInner } from './GetVehicles200ResponseDataNationsInnerVehicleTypesInner.js';
import {
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSON,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSONTyped,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSON,
    GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSONTyped,
} from './GetVehicles200ResponseDataNationsInnerVehicleTypesInner.js';

/**
 * 
 * @export
 * @interface GetVehicles200ResponseDataNationsInner
 */
export interface GetVehicles200ResponseDataNationsInner {
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200ResponseDataNationsInner
     */
    nation: string;
    /**
     * 
     * @type {Array<GetVehicles200ResponseDataNationsInnerVehicleTypesInner>}
     * @memberof GetVehicles200ResponseDataNationsInner
     */
    vehicleTypes: Array<GetVehicles200ResponseDataNationsInnerVehicleTypesInner>;
}

/**
 * Check if a given object implements the GetVehicles200ResponseDataNationsInner interface.
 */
export function instanceOfGetVehicles200ResponseDataNationsInner(value: object): value is GetVehicles200ResponseDataNationsInner {
    if (!('nation' in value) || value['nation'] === undefined) return false;
    if (!('vehicleTypes' in value) || value['vehicleTypes'] === undefined) return false;
    return true;
}

export function GetVehicles200ResponseDataNationsInnerFromJSON(json: any): GetVehicles200ResponseDataNationsInner {
    return GetVehicles200ResponseDataNationsInnerFromJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVehicles200ResponseDataNationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'nation': json['nation'],
        'vehicleTypes': ((json['vehicleTypes'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerVehicleTypesInnerFromJSON)),
    };
}

export function GetVehicles200ResponseDataNationsInnerToJSON(json: any): GetVehicles200ResponseDataNationsInner {
    return GetVehicles200ResponseDataNationsInnerToJSONTyped(json, false);
}

export function GetVehicles200ResponseDataNationsInnerToJSONTyped(value?: GetVehicles200ResponseDataNationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nation': value['nation'],
        'vehicleTypes': ((value['vehicleTypes'] as Array<any>).map(GetVehicles200ResponseDataNationsInnerVehicleTypesInnerToJSON)),
    };
}

export const GetVehicles200ResponseDataNationsInnerPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

