/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetVehicles200ResponseData } from './GetVehicles200ResponseData.js';
import {
    GetVehicles200ResponseDataFromJSON,
    GetVehicles200ResponseDataFromJSONTyped,
    GetVehicles200ResponseDataToJSON,
    GetVehicles200ResponseDataToJSONTyped,
} from './GetVehicles200ResponseData.js';

/**
 * 
 * @export
 * @interface GetVehicles200Response
 */
export interface GetVehicles200Response {
    /**
     * 
     * @type {GetVehicles200ResponseData}
     * @memberof GetVehicles200Response
     */
    data: GetVehicles200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof GetVehicles200Response
     */
    status: string;
}

/**
 * Check if a given object implements the GetVehicles200Response interface.
 */
export function instanceOfGetVehicles200Response(value: object): value is GetVehicles200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetVehicles200ResponseFromJSON(json: any): GetVehicles200Response {
    return GetVehicles200ResponseFromJSONTyped(json, false);
}

export function GetVehicles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVehicles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetVehicles200ResponseDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function GetVehicles200ResponseToJSON(json: any): GetVehicles200Response {
    return GetVehicles200ResponseToJSONTyped(json, false);
}

export function GetVehicles200ResponseToJSONTyped(value?: GetVehicles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetVehicles200ResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const GetVehicles200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

