/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SearchPlayersAndClans200ResponseDataClans } from './SearchPlayersAndClans200ResponseDataClans.js';
import {
    SearchPlayersAndClans200ResponseDataClansFromJSON,
    SearchPlayersAndClans200ResponseDataClansFromJSONTyped,
    SearchPlayersAndClans200ResponseDataClansToJSON,
    SearchPlayersAndClans200ResponseDataClansToJSONTyped,
} from './SearchPlayersAndClans200ResponseDataClans.js';
import type { SearchPlayersAndClans200ResponseDataPlayers } from './SearchPlayersAndClans200ResponseDataPlayers.js';
import {
    SearchPlayersAndClans200ResponseDataPlayersFromJSON,
    SearchPlayersAndClans200ResponseDataPlayersFromJSONTyped,
    SearchPlayersAndClans200ResponseDataPlayersToJSON,
    SearchPlayersAndClans200ResponseDataPlayersToJSONTyped,
} from './SearchPlayersAndClans200ResponseDataPlayers.js';

/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseData
 */
export interface SearchPlayersAndClans200ResponseData {
    /**
     * 
     * @type {SearchPlayersAndClans200ResponseDataClans}
     * @memberof SearchPlayersAndClans200ResponseData
     */
    clans: SearchPlayersAndClans200ResponseDataClans;
    /**
     * 
     * @type {SearchPlayersAndClans200ResponseDataPlayers}
     * @memberof SearchPlayersAndClans200ResponseData
     */
    players: SearchPlayersAndClans200ResponseDataPlayers;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseData interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseData(value: object): value is SearchPlayersAndClans200ResponseData {
    if (!('clans' in value) || value['clans'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseDataFromJSON(json: any): SearchPlayersAndClans200ResponseData {
    return SearchPlayersAndClans200ResponseDataFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'clans': SearchPlayersAndClans200ResponseDataClansFromJSON(json['clans']),
        'players': SearchPlayersAndClans200ResponseDataPlayersFromJSON(json['players']),
    };
}

export function SearchPlayersAndClans200ResponseDataToJSON(json: any): SearchPlayersAndClans200ResponseData {
    return SearchPlayersAndClans200ResponseDataToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataToJSONTyped(value?: SearchPlayersAndClans200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clans': SearchPlayersAndClans200ResponseDataClansToJSON(value['clans']),
        'players': SearchPlayersAndClans200ResponseDataPlayersToJSON(value['players']),
    };
}

export const SearchPlayersAndClans200ResponseDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

