/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SearchPlayersAndClans200ResponseData } from './SearchPlayersAndClans200ResponseData.js';
import {
    SearchPlayersAndClans200ResponseDataFromJSON,
    SearchPlayersAndClans200ResponseDataFromJSONTyped,
    SearchPlayersAndClans200ResponseDataToJSON,
    SearchPlayersAndClans200ResponseDataToJSONTyped,
} from './SearchPlayersAndClans200ResponseData.js';

/**
 * 
 * @export
 * @interface SearchPlayersAndClans200Response
 */
export interface SearchPlayersAndClans200Response {
    /**
     * 
     * @type {object}
     * @memberof SearchPlayersAndClans200Response
     */
    meta: object;
    /**
     * 
     * @type {SearchPlayersAndClans200ResponseData}
     * @memberof SearchPlayersAndClans200Response
     */
    data: SearchPlayersAndClans200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200Response
     */
    status: string;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200Response interface.
 */
export function instanceOfSearchPlayersAndClans200Response(value: object): value is SearchPlayersAndClans200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseFromJSON(json: any): SearchPlayersAndClans200Response {
    return SearchPlayersAndClans200ResponseFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'],
        'data': SearchPlayersAndClans200ResponseDataFromJSON(json['data']),
        'status': json['status'],
    };
}

export function SearchPlayersAndClans200ResponseToJSON(json: any): SearchPlayersAndClans200Response {
    return SearchPlayersAndClans200ResponseToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseToJSONTyped(value?: SearchPlayersAndClans200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': value['meta'],
        'data': SearchPlayersAndClans200ResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

export const SearchPlayersAndClans200ResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

