/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo
 */
export interface SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo {
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo
     */
    id?: number;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo(value: object): value is SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo {
    return true;
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSON(json: any): SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo {
    return SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSON(json: any): SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo {
    return SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSONTyped(value?: SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'color': value['color'],
        'id': value['id'],
    };
}

export const SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

