/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SearchPlayersAndClans200ResponseDataPlayersDataInner } from './SearchPlayersAndClans200ResponseDataPlayersDataInner.js';
import {
    SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSON,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSONTyped,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSON,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSONTyped,
} from './SearchPlayersAndClans200ResponseDataPlayersDataInner.js';

/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseDataPlayers
 */
export interface SearchPlayersAndClans200ResponseDataPlayers {
    /**
     * 
     * @type {number}
     * @memberof SearchPlayersAndClans200ResponseDataPlayers
     */
    total: number;
    /**
     * 
     * @type {Array<SearchPlayersAndClans200ResponseDataPlayersDataInner>}
     * @memberof SearchPlayersAndClans200ResponseDataPlayers
     */
    data: Array<SearchPlayersAndClans200ResponseDataPlayersDataInner>;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataPlayers
     */
    status: string;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseDataPlayers interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseDataPlayers(value: object): value is SearchPlayersAndClans200ResponseDataPlayers {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseDataPlayersFromJSON(json: any): SearchPlayersAndClans200ResponseDataPlayers {
    return SearchPlayersAndClans200ResponseDataPlayersFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseDataPlayers {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSON)),
        'status': json['status'],
    };
}

export function SearchPlayersAndClans200ResponseDataPlayersToJSON(json: any): SearchPlayersAndClans200ResponseDataPlayers {
    return SearchPlayersAndClans200ResponseDataPlayersToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersToJSONTyped(value?: SearchPlayersAndClans200ResponseDataPlayers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSON)),
        'status': value['status'],
    };
}

export const SearchPlayersAndClans200ResponseDataPlayersPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

