/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseDataClansDataInner
 */
export interface SearchPlayersAndClans200ResponseDataClansDataInner {
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataClansDataInner
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataClansDataInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataClansDataInner
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof SearchPlayersAndClans200ResponseDataClansDataInner
     */
    id: number;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseDataClansDataInner interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseDataClansDataInner(value: object): value is SearchPlayersAndClans200ResponseDataClansDataInner {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseDataClansDataInnerFromJSON(json: any): SearchPlayersAndClans200ResponseDataClansDataInner {
    return SearchPlayersAndClans200ResponseDataClansDataInnerFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataClansDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseDataClansDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'name': json['name'],
        'color': json['color'],
        'id': json['id'],
    };
}

export function SearchPlayersAndClans200ResponseDataClansDataInnerToJSON(json: any): SearchPlayersAndClans200ResponseDataClansDataInner {
    return SearchPlayersAndClans200ResponseDataClansDataInnerToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataClansDataInnerToJSONTyped(value?: SearchPlayersAndClans200ResponseDataClansDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'name': value['name'],
        'color': value['color'],
        'id': value['id'],
    };
}

export const SearchPlayersAndClans200ResponseDataClansDataInnerPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

