/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo } from './SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo.js';
import {
    SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSON,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSONTyped,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSON,
    SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSONTyped,
} from './SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo.js';

/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseDataPlayersDataInner
 */
export interface SearchPlayersAndClans200ResponseDataPlayersDataInner {
    /**
     * 
     * @type {number}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInner
     */
    account_id: number;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInner
     */
    nickname: string;
    /**
     * 
     * @type {SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo}
     * @memberof SearchPlayersAndClans200ResponseDataPlayersDataInner
     */
    clan_info: SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfo;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseDataPlayersDataInner interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseDataPlayersDataInner(value: object): value is SearchPlayersAndClans200ResponseDataPlayersDataInner {
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('clan_info' in value) || value['clan_info'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSON(json: any): SearchPlayersAndClans200ResponseDataPlayersDataInner {
    return SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseDataPlayersDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'account_id': json['account_id'],
        'nickname': json['nickname'],
        'clan_info': SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoFromJSON(json['clan_info']),
    };
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSON(json: any): SearchPlayersAndClans200ResponseDataPlayersDataInner {
    return SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataPlayersDataInnerToJSONTyped(value?: SearchPlayersAndClans200ResponseDataPlayersDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['account_id'],
        'nickname': value['nickname'],
        'clan_info': SearchPlayersAndClans200ResponseDataPlayersDataInnerClanInfoToJSON(value['clan_info']),
    };
}

export const SearchPlayersAndClans200ResponseDataPlayersDataInnerPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

