/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SearchPlayersAndClans200ResponseDataClansDataInner } from './SearchPlayersAndClans200ResponseDataClansDataInner.js';
import {
    SearchPlayersAndClans200ResponseDataClansDataInnerFromJSON,
    SearchPlayersAndClans200ResponseDataClansDataInnerFromJSONTyped,
    SearchPlayersAndClans200ResponseDataClansDataInnerToJSON,
    SearchPlayersAndClans200ResponseDataClansDataInnerToJSONTyped,
} from './SearchPlayersAndClans200ResponseDataClansDataInner.js';

/**
 * 
 * @export
 * @interface SearchPlayersAndClans200ResponseDataClans
 */
export interface SearchPlayersAndClans200ResponseDataClans {
    /**
     * 
     * @type {number}
     * @memberof SearchPlayersAndClans200ResponseDataClans
     */
    total: number;
    /**
     * 
     * @type {Array<SearchPlayersAndClans200ResponseDataClansDataInner>}
     * @memberof SearchPlayersAndClans200ResponseDataClans
     */
    data: Array<SearchPlayersAndClans200ResponseDataClansDataInner>;
    /**
     * 
     * @type {string}
     * @memberof SearchPlayersAndClans200ResponseDataClans
     */
    status: string;
}

/**
 * Check if a given object implements the SearchPlayersAndClans200ResponseDataClans interface.
 */
export function instanceOfSearchPlayersAndClans200ResponseDataClans(value: object): value is SearchPlayersAndClans200ResponseDataClans {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SearchPlayersAndClans200ResponseDataClansFromJSON(json: any): SearchPlayersAndClans200ResponseDataClans {
    return SearchPlayersAndClans200ResponseDataClansFromJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataClansFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPlayersAndClans200ResponseDataClans {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'data': ((json['data'] as Array<any>).map(SearchPlayersAndClans200ResponseDataClansDataInnerFromJSON)),
        'status': json['status'],
    };
}

export function SearchPlayersAndClans200ResponseDataClansToJSON(json: any): SearchPlayersAndClans200ResponseDataClans {
    return SearchPlayersAndClans200ResponseDataClansToJSONTyped(json, false);
}

export function SearchPlayersAndClans200ResponseDataClansToJSONTyped(value?: SearchPlayersAndClans200ResponseDataClans | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'data': ((value['data'] as Array<any>).map(SearchPlayersAndClans200ResponseDataClansDataInnerToJSON)),
        'status': value['status'],
    };
}

export const SearchPlayersAndClans200ResponseDataClansPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

