/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PlayerStats } from './PlayerStats.js';
import {
    PlayerStatsFromJSON,
    PlayerStatsFromJSONTyped,
    PlayerStatsToJSON,
    PlayerStatsToJSONTyped,
} from './PlayerStats.js';

/**
 * 
 * @export
 * @interface TankAchievementsData
 */
export interface TankAchievementsData {
    /**
     * 
     * @type {Array<PlayerStats>}
     * @memberof TankAchievementsData
     */
    players: Array<PlayerStats>;
    /**
     * 
     * @type {object}
     * @memberof TankAchievementsData
     */
    extra: object;
}

/**
 * Check if a given object implements the TankAchievementsData interface.
 */
export function instanceOfTankAchievementsData(value: object): value is TankAchievementsData {
    if (!('players' in value) || value['players'] === undefined) return false;
    if (!('extra' in value) || value['extra'] === undefined) return false;
    return true;
}

export function TankAchievementsDataFromJSON(json: any): TankAchievementsData {
    return TankAchievementsDataFromJSONTyped(json, false);
}

export function TankAchievementsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TankAchievementsData {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(PlayerStatsFromJSON)),
        'extra': json['extra'],
    };
}

export function TankAchievementsDataToJSON(json: any): TankAchievementsData {
    return TankAchievementsDataToJSONTyped(json, false);
}

export function TankAchievementsDataToJSONTyped(value?: TankAchievementsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': ((value['players'] as Array<any>).map(PlayerStatsToJSON)),
        'extra': value['extra'],
    };
}

export const TankAchievementsDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

